---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST: database-1.coaptdfq0g1p.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: postgres
    - TYPEORM_DATABASE: database-1

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: yes
      apt:
        name: python3
        state: latest
        update_cache: yes

  # Get the environment variables from CircleCI and add to the EC2 instance
#  environment:
 # - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
  #- TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
  #- TYPEORM_PORT: 5432
  #- TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
  #- TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
  #- TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"


  roles:
    - configure-server
    - configure-prometheus-node-exporter