---
  - name: "show remote environment"
    shell: env

  - name: "Copy backend Files"
    copy:
      src: .backend.tar.gz
      dest: /home/ubuntu

  - name: "unarchive the dist directory"
    unarchive:
      src: .backend.tar.gz
      dest: /home/ubuntu
      copy: no

  - name: "Install Dependencies"
    shell: |
      cd /home/ubuntu/backend
      npm install
      npm run build

  - name: "run server"
    shell: |
      cd .backend
      pm2 start npm --name backend -- start
      pm2 ls